name: docker image build

on:
  push:
    - main:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Spring Boot Application
        run: ./mvnw clean package -DskipTests

      - name: Build Dopcker Image
        run: docker build -t milk-app .